### ISSUE TITLE
Support stacked position option in line layers

### ISSUE THREAD

**Issue by chnn** [influxdata/giraffe#43]
Similar to the `position` option in a histogram layer config, we should support a `position` option in line layer configs.

```
type LinePosition = 'overlaid' | 'stacked'
```

It should default to `'overlaid'`.

The stacking logic should take place in a stat. We may have to refactor the `collectLineData` and `simplifyLineData` utils in the line layer to make this all work out.

**Comment by chnn** [comment]
I did some investigation.

- We can either build the stacking transform ourselves, or [use d3](https://github.com/d3/d3-shape#stacks)
- d3 outputs data in a row-oriented format that will be a pain to integrate with our current `PlotEnv` / `Table` interfaces
- There's [a lot of fantastic parameters to a stacked line graph](http://leebyron.com/streamgraph/stackedgraphs_byron_wattenberg.pdf) that encourage different visualization insights. I would love to expose some of these parameters in the line layer config

**Comment by TCL735** [comment]
Building our own stacking transform is the easiest way to go.

Separately, other challenges to consider:
- shading each layer with its own color rather than the resulting of color of the stacked layers
- line hover tooltip will reflect the cumulative value
- do we need a separate column in the hover tooltip for the original single value (non-cumulative)?
