### ISSUE TITLE
Annotations: Tweak Click Target

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/giraffe#516]
The click target is kind of hard to click on. Let's tweak it to make it easier.

**Comment by ChitlangeSahas** [comment]
Current finding: 

The little div element is getting in the way of our click target. 

![image](https://user-images.githubusercontent.com/18511823/112695607-a78d3600-8e41-11eb-9cad-9ef52534dbc0.png)

There are a couple of solutions possible, one is to move the tooltip up by 5 more pixels, but that seems hacky so I will try shortening the div that is covering it since it looks like half of it is empty anyway. I'll also try to mess with the Z-index and see if that helps.
