### ISSUE TITLE
Folder structure is confusing

### ISSUE THREAD

**Issue by kelwang** [influxdata/giraffe#60]
We should create an easier folder structure, like each vis type belongs to one folder, and a simple config file for create a new type.

**Comment by russorat** [comment]
@chnn what are your thoughts here?

**Comment by chnn** [comment]
We've started to move in the direction where not every layer type has a corresponding components, and some components share implementation. So while I generally like the idea of organizing by functionality rather than unit type, it's not super obvious how to do it here. I also expect the architecture to change again, so I don't think it's worth putting much thought into at present. I'll keep this issue in mind next time we make a big change to see if there's anything we can do.

Closing for now since I don't think there's any immediate action that should be taken.
