### ISSUE TITLE
Visualizations don't support fill of _time

### ISSUE THREAD

**Issue by genehynson** [influxdata/giraffe#681]
If I set `fill: ['_time']`, it breaks most (if not all) visualizations. Here is an example of the line chart:

![image](https://user-images.githubusercontent.com/6411855/134598388-ced4cb61-365c-4440-8412-e5e738ce55e2.png)

I pushed my changes to storybook that recreate this issue here: https://github.com/influxdata/giraffe/tree/genehynson/repo-time-bug

Also see:
- EAR: https://github.com/influxdata/EAR/issues/2599
- Slack: https://influxdata.slack.com/archives/CLHATC50E/p1632432815216800

**Comment by genehynson** [comment]
I think what I'd expect to see in this situation is a bunch of lines where the start and end point of those lines are always equal - so basically a scatter plot.

**Comment by TCL735** [comment]
This issue won't fix the underlying issue in https://github.com/influxdata/EAR/issues/2599 because the issue there is that a line is not being rendered.

So, even if Giraffe were to render dots for lines that have only data point each, and we then see a scatter plot-like visualization, that would not be what the storage trend should look like.

I would say this is an entirely separate issue, and is summarized as follows:
Giraffe line graphs do not render dots for single points of data for each line.

**Comment by TCL735** [comment]
`fill` can be loosely defined as "a column that makes a group of data unique" such as a line. Thus, the `fill` property defines the different lines in a set of data, grouping the data into different lines.

If time is used in `fill` this would cause the grouping to be unique by time, which makes the x-axis look very weird (you would see a bunch of vertical lines) or you would need the x-axis to be something else other than time. Generally this use case is not directly supported by Giraffe. There may be many ancillary bugs and unresolved issues when the x-axis is not time.

Since this is very unconventional, I am closing this issue.
